(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/uni-popup/uni-popup"],{"12e0":function(t,n,i){},3955:function(t,n,i){"use strict";i.d(n,"b",(function(){return e})),i.d(n,"c",(function(){return s})),i.d(n,"a",(function(){return o}));var o={uniTransition:function(){return i.e("components/uni-transition/uni-transition").then(i.bind(null,"a64e"))}},e=function(){var t=this,n=t.$createElement;t._self._c},s=[]},3982:function(t,n,i){"use strict";i.r(n);var o=i("3955"),e=i("aa55");for(var s in e)"default"!==s&&function(t){i.d(n,t,(function(){return e[t]}))}(s);i("44a9");var a,r=i("f0c5"),u=Object(r["a"])(e["default"],o["b"],o["c"],!1,null,"1e34364e",null,!1,o["a"],a);n["default"]=u.exports},"44a9":function(t,n,i){"use strict";var o=i("12e0"),e=i.n(o);e.a},"5b35":function(t,n,i){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var o=function(){i.e("components/uni-transition/uni-transition").then(function(){return resolve(i("a64e"))}.bind(null,i)).catch(i.oe)},e={name:"UniPopup",components:{uniTransition:o},props:{animation:{type:Boolean,default:!0},type:{type:String,default:"center"},top:{type:Number,default:0},left:{type:Number,default:0},maskClick:{type:Boolean,default:!0}},data:function(){return{duration:300,ani:[],showPopup:!1,showTrans:!1,maskClass:{position:"fixed",bottom:0,top:0,left:0,right:0,backgroundColor:"rgba(0, 0, 0, 0.4)"},transClass:{position:"fixed",left:0,right:0,top:0}}},watch:{top:{handler:function(t){this.transClass={position:"fixed",left:this.left+"px",top:t+"px"}}},type:{handler:function(t){switch(this.type){case"top":this.ani=["slide-top"],this.transClass={position:"fixed",left:0,right:0};break;case"bottom":this.ani=["slide-bottom"],this.transClass={position:"fixed",left:0,right:0,bottom:0};break;case"center":this.ani=["zoom-out","fade"],this.transClass={position:"fixed",display:"flex",flexDirection:"column",bottom:0,left:0,right:0,top:0,justifyContent:"center",alignItems:"center"};break;case"position":this.ani=["zoom-out","fade"],this.transClass={position:"fixed",left:this.left,top:this.top};break}},immediate:!0}},created:function(){this.animation?this.duration=300:this.duration=0},methods:{clear:function(t){t.stopPropagation()},open:function(){var t=this;this.showPopup=!0,this.$nextTick((function(){clearTimeout(t.timer),t.timer=setTimeout((function(){t.showTrans=!0}),50)})),this.$emit("change",{show:!0}),this.$emit("noshow",this.showPopup)},close:function(t){var n=this;this.showTrans=!1,this.$nextTick((function(){clearTimeout(n.timer),n.timer=setTimeout((function(){n.$emit("change",{show:!1}),n.showPopup=!1,n.$emit("noshow",n.showPopup)}),300)}))},onTap:function(){this.maskClick&&this.close()}}};n.default=e},aa55:function(t,n,i){"use strict";i.r(n);var o=i("5b35"),e=i.n(o);for(var s in o)"default"!==s&&function(t){i.d(n,t,(function(){return o[t]}))}(s);n["default"]=e.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/uni-popup/uni-popup-create-component',
    {
        'components/uni-popup/uni-popup-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("3982"))
        })
    },
    [['components/uni-popup/uni-popup-create-component']]
]);
