(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/shuvodlist/shuvodlist"],{"6cf4":function(t,n,e){"use strict";e.r(n);var r=e("83de"),i=e("7236");for(var o in i)"default"!==o&&function(t){e.d(n,t,(function(){return i[t]}))}(o);e("89bb");var u,a=e("f0c5"),c=Object(a["a"])(i["default"],r["b"],r["c"],!1,null,null,null,!1,r["a"],u);n["default"]=c.exports},7236:function(t,n,e){"use strict";e.r(n);var r=e("ad70"),i=e.n(r);for(var o in r)"default"!==o&&function(t){e.d(n,t,(function(){return r[t]}))}(o);n["default"]=i.a},"7f08":function(t,n,e){},"83de":function(t,n,e){"use strict";var r;e.d(n,"b",(function(){return i})),e.d(n,"c",(function(){return o})),e.d(n,"a",(function(){return r}));var i=function(){var t=this,n=t.$createElement;t._self._c},o=[]},"89bb":function(t,n,e){"use strict";var r=e("7f08"),i=e.n(r);i.a},ad70:function(t,n,e){"use strict";(function(t){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var r=i(e("a34a"));function i(t){return t&&t.__esModule?t:{default:t}}function o(t,n,e,r,i,o,u){try{var a=t[o](u),c=a.value}catch(f){return void e(f)}a.done?n(c):Promise.resolve(c).then(r,i)}function u(t){return function(){var n=this,e=arguments;return new Promise((function(r,i){var u=t.apply(n,e);function a(t){o(u,r,i,a,c,"next",t)}function c(t){o(u,r,i,a,c,"throw",t)}a(void 0)}))}}var a={name:"shuvodlist",data:function(){return{WxVerify:!0,picError:!1,picLoad:!1,showImg:!1,vod_content:""}},props:{item:{type:Object,defual:function(){return[]}},lishi:{type:Boolean,default:!0},theme:{type:[String],default:"white"}},created:function(){this.item.vod_content&&(this.vod_content=this.item.vod_content.replace(/<[^bai>]+>/g,""))},mounted:function(){var t=this;return u(r.default.mark((function n(){return r.default.wrap((function(n){while(1)switch(n.prev=n.next){case 0:t.WxVerify=getApp().globalData.$wxverify;case 1:case"end":return n.stop()}}),n)})))()},methods:{play:function(n){t.navigateTo({url:"../detail/detail?id="+n})},imgload:function(t){this.showImg=!0},imgError:function(t){this.picError=!0}}};n.default=a}).call(this,e("543d")["default"])}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/shuvodlist/shuvodlist-create-component',
    {
        'components/shuvodlist/shuvodlist-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("6cf4"))
        })
    },
    [['components/shuvodlist/shuvodlist-create-component']]
]);
